repo: places.atgeo.org
databases:
  - type: foursquare
    path: db/fsq-osp.duckdb
  - type: overture_place
    path: db/overture-maps.duckdb

tiles:
  max_per_tile: 1000
  memory_limit: 48GB
  collections:
    org.atgeo.places.foursquare:
      slug: foursquare
      manifest: tiles/foursquare/tiles/current/manifest.duckdb
      tiles_dir: tiles/foursquare/tiles/current
      base_url: https://places.atgeo.org/tiles/foursquare
      attribution: https://docs.foursquare.com/data-products/docs/access-fsq-os-places
      cache_ttl: 86400
    org.atgeo.places.overture.place:
      slug: overture-place
      manifest: tiles/overture_place/tiles/current/manifest.duckdb
      tiles_dir: tiles/overture_place/tiles/current
      base_url: https://places.atgeo.org/tiles/overture-place
      attribution: https://docs.overturemaps.org/attribution/
      cache_ttl: 86400
    org.atgeo.places.osm:
      slug: osm
      manifest: tiles/osm/tiles/current/manifest.duckdb
      tiles_dir: tiles/osm/tiles/current
      base_url: https://places.atgeo.org/tiles/osm
      attribution: https://www.openstreetmap.org/copyright
      cache_ttl: 86400
  max_coverage_tiles: 50
